version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - .:/var/www/html
            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        environment:
            - VIRTUAL_HOST=app.takebook.local
            - VIRTUAL_PORT=80
        depends_on:
            - web
        networks:
            - takebook-network
        working_dir: /var/www/html
    web:
        image: node
        container_name: takebook_adm
        build: .
        ports:
            - '3000:3000'
        volumes:
            - .:/var/www/html
        networks:
            - takebook-network

networks:
    takebook-network:
        driver: bridge
