version: '3'

services:
    web:
        image: node
        container_name: takebook_adm
        build: .
        ports:
            - '3000:3000'
        volumes:
            - .:/var/www/html
        networks:
            - takebook-network

networks:
    takebook-network:
        driver: bridge
